import numpy as np
from copy import deepcopy

# Begins here
# ?
shchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch = "shchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch"; shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch = ord; shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch = int; shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch = chr; shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshcho = str; shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchsho = max; shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchohshchsho = min
shchshchshchshchshchshchshchshchshchshchshohshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch = "___________"
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch = 0
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshoh = 1
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshch = 2
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshch = 3
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshch = 4
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshch = 5
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshch = 6
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshch = 7
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshch = 8
shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshch = 9

def shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshc(shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch):
    shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchsh = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc
    shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshcsh = -1
    if shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc == 0:
        return 0, 0

    elif shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc >= 0:
        while shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc >= 0:
            shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc -= shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch
            shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshcsh += 1
    else:
        shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshcsh = 0
        while shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc < 0:
            shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc += shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch
            shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshcsh -= 1
    return shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshcsh, (shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchsh - shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshcsh * shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch)

def shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch(shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchch="o"):
    ___________________________________ = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchch); shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch = 0
    for shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch in shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch:
        ___________________________________ = ___________________________________ + 1
        shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch + shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch
    return ___________________________________, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch

def __________________________________(arr, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshch):
    shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch(arr, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchch="о")

    shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc[shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(48))]

    for whatever in shchshchshchshchshchshchshchshchshchshchshohshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch:
        shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc -= shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(whatever)
        shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc -= shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(51))
    __ = [shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(48))] * (shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc - shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(56)))

    ___ = [shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(48))] * (10)


    for i in range(0, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc - shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(56))):
        index = arr[i] // shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshch
        ___[index % (shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshch + shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshch)] += shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshoh


    for i in range(1, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshch + 1):
        ___[i] += ___[i - 1]

    i = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshc - shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(56)) - 1
    while i >= 0:
        shohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchc, shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchc = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshc(arr[i], shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshch)
        ____ = shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshc(shohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchc, 10)[shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(49))]
        __[___[____] - shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshoh] = arr[i]
        ___[____] -= shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshoh
        i -= shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshoh

    for i in range(0, len(arr)):
        arr[i] = __[i]

# This is bubble sort, I PROMISE!
def shch(arr):

    _1 = shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchsho(arr)
    _ = shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(49))
    while shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshc(_1, _)[shchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshch] >= 1:
        __________________________________(arr, _)
        _ *= shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshcho(shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(49))) + shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshcho(shchshchshchshchshchshohshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(shchshchshchshchshchshohshchshchshchshchschhshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchshchchshchshch(48))))

def sort_starts_here(arr):
    array_neg = np.asarray([i for i in arr if i < 0]) * -1
    array_pos = np.asarray([i for i in arr if i >= 0])
    if len(array_neg) > 0:
        shch(array_neg)
    if len(array_pos) > 0:
        shch(array_pos)
    arr = np.append(array_neg[::-1] * -1, array_pos)
    return arr

# Ends here


array = np.random.randint(low=-10000, high=10000, size=1000)
array_ = deepcopy(array)

array = sort_starts_here(array)
array_.sort()

print(np.array_equal(array, array_))
